/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userGUI;
import client_server.Client;
import java.io.IOException;
import java.text.ParseException;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import javax.swing.JTextField;
import memoassistant.*;
import static userGUI.mainFrame.USER_EMAIL;
/**
 *
 * @author Alessandro
 */
public class editFavorites extends mainFrame {

    
   private int idfavorites;
   private Double latitude;
   private Double longitude;
   
    /**
     * Creates new form newFavorites
     */
    public editFavorites() {
        initComponents();        
        nameTF.requestFocus();
    }

    public editFavorites(Favorites favorites) {
        initComponents();
        nameTF.requestFocus();
        idfavorites = favorites.getIdfavorites();
        latitude = favorites.getLatitude();
        longitude = favorites.getLongitude();
        loadFavorites(favorites);
    }
    
       /*public boolean createFavorites(){
        
        //Point2D.Double coord = new Point2D.Double(16, 12);
        Favorites favorites = new Favorites();
        
        favorites.setLatitude(16.0);
        favorites.setLongitude(12.0);
        favorites.setAddress(addressTF.getText());
        favorites.setDescription(nameTF.getText());
       
        if (!validInput()){
            JOptionPane.showMessageDialog(this, "All fields are required, please", "Error invalid input", ERROR_MESSAGE);
            return false;
            }
        
        LinkedList<Favorites> list = new LinkedList<>();
        list.add(favorites);
        
        Client client = new Client();
        client.send(list, "New", USER_EMAIL);
        client.closeSocket();
        
        return true;
    }*/

    
    public boolean updateFavorites(){
       try {
           Favorites favorites = new Favorites();
           favorites.setIdfavorites(idfavorites);
           favorites.setLatitude(latitude);
           favorites.setLongitude(longitude);
           favorites.setDescription(nameTF.getText());
           favorites.setAddress(addressTF.getText());
           
           
           if (!validInput()){
               JOptionPane.showMessageDialog(this, "All fields are required, please", "Error invalid input", ERROR_MESSAGE);
               return false;
           }
           
           LinkedList<Favorites> list = new LinkedList<>();
           list.add(favorites);
           
           Client client = new Client();
           client.send(list, "Update", null);
           client.closeSocket();
           
           return true;
       } catch (IOException ex) {
           JOptionPane.showMessageDialog(null, "Server out of services", ex.getMessage(), JOptionPane.ERROR_MESSAGE);
           return false;
       }
    
    }
    
     private boolean validInput(){
        return (!nameTF.getText().equals("")) && (!addressTF.getText().equals(""));
    }
    
    private void loadFavorites(Favorites favorites){
    
        nameTF.setText(favorites.getDescription());
        addressTF.setText(favorites.getAddress());
        
       
    }
    
      
    public void setNameButton(String name){
    
      CreateButton.setText(name);
    }
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSfondo = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        addressTF = new javax.swing.JTextField();
        nameTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        advLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        CreateButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Favorites");
        setResizable(false);

        jPanelSfondo.setOpaque(false);
        jPanelSfondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        jLabel3.setText("Address: ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, 30));

        addressTF.setPreferredSize(new java.awt.Dimension(260, 30));
        addressTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addressTFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addressTFFocusLost(evt);
            }
        });
        jPanel2.add(addressTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 320, -1));

        nameTF.setPreferredSize(new java.awt.Dimension(80, 35));
        jPanel2.add(nameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 180, 30));

        jLabel4.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        jLabel4.setText("Insert a name:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 30));

        advLabel.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        advLabel.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.add(advLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 240, -1));

        jPanelSfondo.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 440, 120));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        CreateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userGUI/resources/ok-26.png"))); // NOI18N
        CreateButton.setText("Apply");
        CreateButton.setName(""); // NOI18N
        CreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateButtonActionPerformed(evt);
            }
        });
        jPanel1.add(CreateButton);

        CancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userGUI/resources/cancel-26 red.png"))); // NOI18N
        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });
        jPanel1.add(CancelButton);

        jPanelSfondo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 440, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userGUI/resources/sfondo 500x550.png"))); // NOI18N
        jPanelSfondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 170));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelSfondo, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSfondo, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateButtonActionPerformed

        /* if (CreateButton.getText().equals("Create")){
            if (createFavorites()){
                JOptionPane.showMessageDialog(this, "Creating favorites successfully completed", 
                        "Completed", JOptionPane.INFORMATION_MESSAGE);
                favoritesScreen fav = new favoritesScreen();
                this.dispose();
                fav.setVisible(true);
            }
        } else{*/
            if(updateFavorites()){
            JOptionPane.showMessageDialog(this, "Updating favorites successfully completed",
                    "Completed", JOptionPane.INFORMATION_MESSAGE);
            favoritesScreen fav = new favoritesScreen();
            
            fav.setVisible(true);
            }
            this.dispose();
        //}
    }//GEN-LAST:event_CreateButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        favoritesScreen fav = new favoritesScreen();
        this.dispose();
        fav.setVisible(true);
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void addressTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressTFFocusGained
        
        advLabel.setText("Change the address does not change the coordinates");
    }//GEN-LAST:event_addressTFFocusGained

    private void addressTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressTFFocusLost
        
        advLabel.setText("");
    }//GEN-LAST:event_addressTFFocusLost

 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editFavorites.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editFavorites.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editFavorites.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editFavorites.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editFavorites().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JButton CreateButton;
    private javax.swing.JTextField addressTF;
    private javax.swing.JLabel advLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelSfondo;
    private javax.swing.JTextField nameTF;
    // End of variables declaration//GEN-END:variables

   
}
