/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userGUI;

import client_server.Client;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.util.Collections;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import memoassistant.Favorites;
import static userGUI.mainFrame.USER_EMAIL;

/**
 *
 * @author Alessandro
 */
public class favoritesScreen extends mainFrame {

    private static LinkedList<Favorites> favoritesList;
    private  DefaultTableModel newModel;
    /**
     * Creates new form favoritesScreen
     */
    public favoritesScreen() {
        initComponents();
        loadFavoritesTable();
    }

    /**
     * Carica la lista dei preferiti e la ordina
     */
    public static void loadFavorites(){
        try {
            Client client = new Client();
            client.send("Favorites", USER_EMAIL);
            favoritesList =  (LinkedList<Favorites>) client.receive();
            Collections.sort(favoritesList);
            client.closeSocket();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Server out of services", ex.getMessage(), JOptionPane.ERROR_MESSAGE);
          }
        
    }

    
    public static LinkedList<Favorites> getFavoritesList() {
        return favoritesList;
    }
    
    /**
     * Carica la tabella con la lista
     */
    public void loadFavoritesTable(){
    
        loadFavorites();
        //firstScreen.stampaList(firstScreen.getFriendsList());
        String[] columnNames = new String [] {
        "Name", "Address", "Latitude", "Longitude" };
        Object[][] data = new Object[favoritesList.size()][4];
        
       
        int i = 0;
        for (Favorites f : favoritesList){
        
            String name = f.getDescription();
            String address = f.getAddress();
            Double latitude = f.getLatitude();
            Double longitude = f.getLongitude();
            
            data[i][0] = name;
            data[i][1] = address;
            data[i][2] = latitude;
            data[i][3] = longitude;
            i++;
        }
        setFavoritesTable(data, columnNames);
    }

    private void setFavoritesTable(Object[][] dataObj, String[] col) {

         newModel = new DefaultTableModel(dataObj, col) {

            @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false
                return false;
            }
        };
        
        favoritesTable.setModel(newModel);
        favoritesTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        addDoubleclickedListener();
    }
    /**
     * Metodo che aggiunge un listener per un doppio click su una riga della tabella
     */
    private  void addDoubleclickedListener() {
        favoritesTable.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    JTable target = (JTable) e.getSource();
                    int row = target.getSelectedRow();
                    int column = target.getSelectedColumn();
                    // do some action
                    JOptionPane.showMessageDialog(null, "idfavorites " + favoritesList.get(row).getIdfavorites());
                    editFavorites newfav = new editFavorites(favoritesList.get(row));
                    dispose();
                    newfav.setVisible(true);
                }
            }
        });
    }
    
      private void deleteFavorites(int i){
        try {
            LinkedList<Favorites> list = new LinkedList<>();
            list.add(favoritesList.get(i));
            Client client = new Client();
            client.send(list, "Delete", USER_EMAIL);
            client.closeSocket();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Server out of services", ex.getMessage(), JOptionPane.ERROR_MESSAGE);
        }
    }
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        favoritesTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Favorites");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userGUI/resources/sfondo 500x30.png"))); // NOI18N
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 30));

        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userGUI/resources/plus-26.png"))); // NOI18N
        addButton.setText("Add");
        addButton.setToolTipText("Add new person");
        addButton.setPreferredSize(new java.awt.Dimension(101, 35));
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        jPanel2.add(addButton);

        removeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userGUI/resources/minus-26.png"))); // NOI18N
        removeButton.setText("Remove");
        removeButton.setToolTipText("Remove  person");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });
        jPanel2.add(removeButton);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 490, -1));

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        favoritesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Address", "Latitude", "Longitude"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(favoritesTable);

        jPanel3.add(jScrollPane2);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 490, 210));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        
        newFavor newfav = new newFavor();
        this.dispose();
        newfav.setVisible(true);
    }//GEN-LAST:event_addButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed

           try{
            int i = favoritesTable.getSelectedRow();
            int result = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete Favorites: " + favoritesList.get(i).getDescription()+ " " + 
                    favoritesList.get(i).getAddress()+ " ?", "Delete Favorites", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
            if (result == JOptionPane.YES_OPTION){
                deleteFavorites(i);
                newModel.removeRow(i);
            }
        }catch (IndexOutOfBoundsException ex){
            JOptionPane.showMessageDialog(this, "No record to delete", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_removeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(favoritesScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(favoritesScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(favoritesScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(favoritesScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new favoritesScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private static javax.swing.JTable favoritesTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton removeButton;
    // End of variables declaration//GEN-END:variables
}
