/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userGUI;

import java.awt.geom.Point2D;
import java.io.UnsupportedEncodingException;
import java.net.MalformedURLException;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import maps.*;

/**
 *
 * @author Alessandro
 */
public class myPosition extends javax.swing.JFrame {

    
    private static Double latitude = 0.0, longitude = 0.0;
    private Geocoding ObjGeocoding;
    private static String addressFound;
    
    /**
     * Creates new form myPosition
     */
    public myPosition() {
        initComponents();
        ObjGeocoding = new Geocoding();
        checkPosition();
    }

    public static Double getLatitude() {
        return latitude;
    }

    public static Double getLongitude() {
        return longitude;
    }

    /**
     * Se è stata trovata una posizione valida, imposta i label
     */
    private void checkPosition(){
    
        if (latitude != 0.0 && longitude != 0.0){
            LatJLabel.setText(String.valueOf(latitude));
            LongJLabel.setText(String.valueOf(longitude));
            addrJLabel.setText(addressFound);
        }
    }
    
    /**
     * Calcola le coordinate dell'indirizzo inserito
     * @throws UnsupportedEncodingException
     * @throws MalformedURLException 
     */
    private void getFromStreet() throws UnsupportedEncodingException, MalformedURLException{
      
       try {
           if (!this.addressTF.getText().isEmpty()) {
               addrJLabel.setText("");
               System.out.println("address inserito: " + addressTF.getText());
               Point2D.Double result = ObjGeocoding.getCoordinates(addressTF.getText());
               if (result == null) {
                   System.out.println("result null");
               }
               System.out.println("sono qui: " + result.toString());
               LatJLabel.setText(String.valueOf(result.x));
               LongJLabel.setText(String.valueOf(result.y));
               addrJLabel.setText(String.valueOf(ObjGeocoding.getAddressFound()));
           }
       }catch (NullPointerException e){
           JOptionPane.showMessageDialog(this, "Check your internet connection", "Error", ERROR_MESSAGE);
       }
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSfondo = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        addressTF = new javax.swing.JTextField();
        findButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        addrJLabel = new javax.swing.JLabel();
        LongJLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        LatJLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("My position (simulated)");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelSfondo.setOpaque(false);
        jPanelSfondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        jLabel4.setText("Address");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        addressTF.setPreferredSize(new java.awt.Dimension(200, 30));
        jPanel4.add(addressTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 5, 250, -1));

        findButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userGUI/resources/lenteblu 16x16.png"))); // NOI18N
        findButton.setToolTipText("");
        findButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findButtonActionPerformed(evt);
            }
        });
        jPanel4.add(findButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 5, -1, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        jLabel6.setText("Address found:");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 80, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        jLabel7.setText("Longitude:");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 50, 30));

        addrJLabel.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        jPanel4.add(addrJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 250, 30));

        LongJLabel.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        jPanel4.add(LongJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 90, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        jLabel8.setText("Latitude:");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 40, 30));

        LatJLabel.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        jPanel4.add(LatJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 70, 30));

        jPanelSfondo.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 380, 90));

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        okButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userGUI/resources/ok-26.png"))); // NOI18N
        okButton.setText("OK");
        okButton.setPreferredSize(new java.awt.Dimension(95, 35));
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        jPanel3.add(okButton);

        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userGUI/resources/cancel-26 red.png"))); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel3.add(cancelButton);

        jPanelSfondo.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 390, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userGUI/resources/sfondo399.png"))); // NOI18N
        jPanelSfondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 140));

        getContentPane().add(jPanelSfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 390, 140));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void findButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findButtonActionPerformed
        try {
                    getFromStreet();
                } catch (UnsupportedEncodingException | MalformedURLException ex) {
                    JOptionPane.showMessageDialog(this, "Error geocoding", ex.getMessage(), ERROR_MESSAGE);
                }
    }//GEN-LAST:event_findButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        
        try {
            getFromStreet();
            if (!addrJLabel.getText().equalsIgnoreCase("No data") && !addrJLabel.getText().equals("")){
                myPosition.latitude = Double.parseDouble(LatJLabel.getText());
                myPosition.longitude = Double.parseDouble(LongJLabel.getText());
                myPosition.addressFound = addrJLabel.getText();
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Address not found. Try again", "Error", ERROR_MESSAGE);
            }
        } catch (UnsupportedEncodingException | MalformedURLException ex) {
            JOptionPane.showMessageDialog(this, "Error geocoding", ex.getMessage(), ERROR_MESSAGE);
        }
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(myPosition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(myPosition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(myPosition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(myPosition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new myPosition().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LatJLabel;
    private javax.swing.JLabel LongJLabel;
    private javax.swing.JLabel addrJLabel;
    private javax.swing.JTextField addressTF;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton findButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelSfondo;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
}
