/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userGUI;

import memoassistant.Action;
import memoassistant.Event;

/**
 *
 * @author Alessandro
 */
public class notice extends javax.swing.JFrame {

    
    
    /**
     * Creates new form notice
     */
    public notice() {
        initComponents();
    }

  public notice(Event event) {
        initComponents();
        DATElabel.setText(String.valueOf(event.getEventDate()));
        HOURlabel.setText(String.valueOf(event.getEventHour()));
        whatTF.setText(event.getWhat());
        WHERElabel.setText(event.getWhere());        
    }
  
  public notice(Action action){
        initComponents();
        DATElabel.setText("");
        dateLab.setText("");
        HOURlabel.setText("");
        hourLab.setText("");
        whatTF.setText(action.getWhat());
        WHERElabel.setText(action.getWhere());
  }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dateLab = new javax.swing.JLabel();
        hourLab = new javax.swing.JLabel();
        whatLab = new javax.swing.JLabel();
        whereLab = new javax.swing.JLabel();
        DATElabel = new javax.swing.JLabel();
        HOURlabel = new javax.swing.JLabel();
        WHERElabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        whatTF = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Remind");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dateLab.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        dateLab.setText("Date:");
        jPanel1.add(dateLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 40, 20));

        hourLab.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        hourLab.setText("Hour:");
        jPanel1.add(hourLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 40, 20));

        whatLab.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        whatLab.setText("What:");
        jPanel1.add(whatLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 40, 20));

        whereLab.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        whereLab.setText("Where:");
        jPanel1.add(whereLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 50, 20));

        DATElabel.setText("jLabel5");
        jPanel1.add(DATElabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 80, 20));

        HOURlabel.setText("jLabel6");
        jPanel1.add(HOURlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 80, 20));

        WHERElabel.setText("jLabel7");
        jPanel1.add(WHERElabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 400, 20));

        whatTF.setColumns(20);
        whatTF.setRows(5);
        whatTF.setEnabled(false);
        jScrollPane1.setViewportView(whatTF);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 66, 410, 90));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4, 500, 160));

        okButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userGUI/resources/ok-26.png"))); // NOI18N
        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        jPanel2.add(okButton);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 500, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(notice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(notice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(notice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(notice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new notice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DATElabel;
    private javax.swing.JLabel HOURlabel;
    private javax.swing.JLabel WHERElabel;
    private javax.swing.JLabel dateLab;
    private javax.swing.JLabel hourLab;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel whatLab;
    private javax.swing.JTextArea whatTF;
    private javax.swing.JLabel whereLab;
    // End of variables declaration//GEN-END:variables
}
